node {
   stage ('Checkout'){
       git 'https://github.com/omarlari/aws-container-migration-workshop.git'
   }

   stage ('Build Dockerfile'){
      dir ('containerize-application'){
        def dockerfile = 'Dockerfile.final'
        docker.build("petstore:${env.BUILD_NUMBER}", "-f ./${dockerfile} .")
      }
   }

   stage ('Push to ECR'){
      sh ("eval \$(docker run awscli aws ecr get-login --region ${REGION} --no-include-email | sed 's|https://||')")
      docker.withRegistry("https://${ECR_REPO}") {
         docker.image("petstore:${env.BUILD_NUMBER}").push()
      }
   }

   stage('Update Application'){
      //sh ("eval \$(docker run -v /home/ec2-user/.kube:/config/.kube kubectl set image deployment/${APP} petstore=${ECR_REPO}/petstore:${BUILD_NUMBER})")
      sh ("docker run -v /home/ec2-user/.kube:/config/.kube kubectl set image deployment/${APP} petstore=${ECR_REPO}/petstore:${env.BUILD_NUMBER}")
   }
}
