Description: >
  This template setups up the work shop.
Parameters:
  KeyName:
    Type: String

Metadata: {}

Resources:

  Cloud9:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/aws-container-migration-workshop/cloud9.yaml
      
  SupportingTools:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/aws-container-migration-workshop/supporting-tools.yaml
      Parameters: {}

  JenkinsVPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/jenkins-demo-public/vpc.yaml
      Parameters: {}

  Jenkins:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/jenkins-demo-public/jenkins.yaml
      Parameters:
        KeyName: !Ref KeyName
        Subnet: !GetAtt JenkinsVPC.Outputs.Subnet
        Vpc: !GetAtt JenkinsVPC.Outputs.VpcId
