Description: >
  This template setups up the work shop.
Parameters:
  KeyName:
    Type: String

Metadata: {}

Resources:

  Cloud9:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/aws-container-migration-workshop/cloud9.yaml

  SupportingTools:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/aws-container-migration-workshop/supporting-tools.yaml
      Parameters: {}

  Jenkins:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/jenkins-demo-public/jenkins.yaml
      Parameters:
        KeyName: !Ref KeyName
        Subnet: !GetAtt Cloud9.Outputs.Subnet1
        Vpc: !GetAtt Cloud9.Outputs.VpcId

Outputs:
  Cloud9Endpoint:
    Value: !GetAtt Cloud9.Outputs.Cloud9IDE
  RDSEndpoint:
    Value: !GetAtt SupportingTools.Outputs.RDSEndpoint
  ECRRepo:
    Value: !GetAtt SupportingTools.Outputs.ECRURL
  JenkinsIP:
    Value: !GetAtt Jenkins.Outputs.PublicIP
