node {

   stage ('Checkout'){
       git 'https://github.com/omarlari/aws-container-migration-workshop.git'
   }

   stage ('Build Dockerfile'){
      dir ('Lab2'){
        def dockerfile = 'Dockerfile.final'
        docker.build("my-image:${env.BUILD_ID}", "-f ./${dockerfile} .")
      }
   }
   }
